# AI Assistance Disclosure:
# Tool: Claude (claude.ai chat, model: Claude Opus 5.5), date: 2026-09-26
# Scope: Generated by Alembic autogenerate from the AI-generated tables.py; the pg_trgm line was added by the AI.
# Author review: <to be completed by author>

"""create suppliers and delivery_locations

Revision ID: b037ea030fac
Revises: 
Create Date: 2026-09-26 01:17:35.140501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b037ea030fac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Added by hand: the keyword-search index (ix_suppliers_search_trgm) needs the
    # pg_trgm extension, which autogenerate doesn't detect. It ships with Postgres.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_locations',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180', name=op.f('ck_delivery_locations_coordinates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_locations'))
    )
    op.create_index('uq_delivery_locations_name_lower', 'delivery_locations', [sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('building', sa.String(length=100), nullable=False),
    sa.Column('floor', sa.String(length=10), nullable=True),
    sa.Column('location_description', sa.String(length=300), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("type IN ('Food', 'Drinks', 'Shopping', 'Printing')", name=op.f('ck_suppliers_type')),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180', name=op.f('ck_suppliers_coordinates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_index('ix_suppliers_building_lower', 'suppliers', [sa.literal_column('lower(building)')], unique=False)
    op.create_index('ix_suppliers_search_trgm', 'suppliers', [sa.literal_column("(name || ' ' || building || ' ' || location_description)").label('search_text')], unique=False, postgresql_using='gin', postgresql_ops={'search_text': 'gin_trgm_ops'})
    op.create_index('ix_suppliers_type', 'suppliers', ['type'], unique=False)
    op.create_index('uq_suppliers_name_lower', 'suppliers', [sa.literal_column('lower(name)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_suppliers_name_lower', table_name='suppliers', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_suppliers_type', table_name='suppliers')
    op.drop_index('ix_suppliers_search_trgm', table_name='suppliers', postgresql_using='gin', postgresql_ops={'search_text': 'gin_trgm_ops'})
    op.drop_index('ix_suppliers_building_lower', table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index('uq_delivery_locations_name_lower', table_name='delivery_locations', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('delivery_locations')
    # ### end Alembic commands ###
